// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arvopbxzeoddkjewfazr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFydm9wYnh6ZW9kZGtqZXdmYXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MTA0MTgsImV4cCI6MjA5MDE4NjQxOH0.Vk8Eljeej3IOLsikTloVJNZrHhXlFgxFx6QV4XDG-7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});